### ISSUE TITLE
Problema com códigos específicos

### ISSUE THREAD

**Issue by jorgesallum** [nichmorgan/SIGEPy#2]
@nichmorgan Nós continuamos com problema aqui com alguns códigos específicos. O 03220 não é aceito pela API. Será que este não é um problema da aplicação?

![image](https://user-images.githubusercontent.com/2036559/105874861-dcb10f80-5fdb-11eb-8704-690193199696.png)

**Comment by nichmorgan** [comment]
Oi, hoje a noite vou dar uma olhada seguindo esse log.

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by nichmorgan** [comment]
Pelo padrão do número passado, 03220, é um código de serviço. Esse por sua vez não está listado dentro da biblioteca que essa aplicação utiliza, a "correios". Essa biblioteca é pública e de terceiro, logo não tenho controle sobre a mesma.

O caminho da captura de tela é: "correios.models.data"

Segue captura de tela com os serviços listados.

![image](https://user-images.githubusercontent.com/55922364/105883440-9eb8e900-5fe5-11eb-8fb5-2bb1005476b6.png)

**Comment by jorgesallum** [comment]
Morgan, essa aplicação "correios" é a python-correios? Você poderia nos
apontar qual é o endereço dela no github? Eu vou tentar falar com eles.

**Comment by nichmorgan** [comment]
O problema não está no python-correios, mas na olist.
https://github.com/olist/correios

**Comment by jorgesallum** [comment]
Obrigado!
